import type { INodeProperties } from 'n8n-workflow';
import { currentSeason } from './Common';

const show = { resource: ['nfl'], operation: ['getPlayerPoints'] };

const positions = [
	'ALL',
	'QB',
	'RB',
	'WR',
	'TE',
	'OT',
	'OL',
	'OG',
	'C',
	'DE',
	'DT',
	'LB',
	'CB',
	'S',
	'DB',
	'K',
	'P',
	'DST',
].map((value) => ({ name: value, value }));

export const nflDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['nfl'] } },
		options: [
			{
				name: 'Get Player Points',
				value: 'getPlayerPoints',
				action: 'Get NFL player points',
				description: 'Get fantasy points for NFL players',
			},
		],
		default: 'getPlayerPoints',
	},
	{
		displayName: 'Season',
		name: 'season',
		type: 'number',
		typeOptions: { minValue: 2012, maxValue: 9999 },
		default: currentSeason,
		required: true,
		displayOptions: { show },
		description: 'NFL season year to request',
	},
	{
		displayName: 'Start Week',
		name: 'startWeek',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 22 },
		default: 1,
		required: true,
		displayOptions: { show },
		description: 'First week to include',
	},
	{
		displayName: 'End Week',
		name: 'endWeek',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 22 },
		default: 18,
		required: true,
		displayOptions: { show },
		description: 'Last week to include',
	},
	{
		displayName: 'Position',
		name: 'position',
		type: 'options',
		options: positions,
		default: 'ALL',
		displayOptions: { show },
		description: 'Player position to include',
	},
	{
		displayName: 'Scoring',
		name: 'scoring',
		type: 'options',
		options: [
			{ name: 'Half PPR', value: 'HALF' },
			{ name: 'PPR', value: 'PPR' },
			{ name: 'Standard', value: 'STD' },
		],
		default: 'STD',
		displayOptions: { show },
		description: 'Scoring system used to calculate points',
	},
	{
		displayName: 'Minimal Response',
		name: 'minimalResponse',
		type: 'boolean',
		default: false,
		displayOptions: { show },
		description: 'Whether to return less player information for a smaller response',
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		displayOptions: { show },
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 50,
		displayOptions: { show: { ...show, returnAll: [false] } },
		description: 'Max number of results to return',
	},
];
