import type { INodeProperties } from 'n8n-workflow';
import { currentSeason, positionOptions, siteEligibilityOptions } from './Common';

const resourceShow = { resource: ['projection'] };
const nflShow = { ...resourceShow, operation: ['getNfl'] };
const mlbShow = { ...resourceShow, operation: ['getMlb'] };
const nbaShow = { ...resourceShow, operation: ['getNba'] };

const projectionTypes = [
	{ name: 'Daily', value: 'daily' },
	{ name: 'Preseason', value: 'preseason' },
	{ name: 'Rest of Season', value: 'ros' },
	{ name: 'Weekly', value: 'weekly' },
];

export const projectionDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: resourceShow },
		options: [
			{
				name: 'Get MLB',
				value: 'getMlb',
				action: 'Get MLB projections',
				description: 'Get MLB player projections',
			},
			{
				name: 'Get NBA',
				value: 'getNba',
				action: 'Get NBA projections',
				description: 'Get NBA player projections',
			},
			{
				name: 'Get NFL',
				value: 'getNfl',
				action: 'Get NFL projections',
				description: 'Get NFL player projections',
			},
		],
		default: 'getNfl',
	},
	{
		displayName: 'Season',
		name: 'season',
		type: 'number',
		typeOptions: { minValue: 2012, numberStepSize: 1 },
		default: currentSeason,
		required: true,
		displayOptions: { show: resourceShow },
		description: 'Four-digit season year',
	},
	{
		displayName: 'Position',
		name: 'position',
		type: 'options',
		options: positionOptions.nfl,
		default: 'QB',
		required: true,
		displayOptions: { show: nflShow },
		description: 'Primary NFL position to request',
	},
	{
		displayName: 'Projection Period',
		name: 'nflProjectionPeriod',
		type: 'options',
		options: [
			{ name: 'Preseason', value: 'preseason' },
			{ name: 'Rest of Season', value: 'ros' },
			{ name: 'Weekly', value: 'weekly' },
		],
		default: 'weekly',
		displayOptions: { show: nflShow },
		description: 'Projection period to request',
	},
	{
		displayName: 'Week',
		name: 'nflWeek',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 22, numberStepSize: 1 },
		default: 1,
		required: true,
		displayOptions: { show: { ...nflShow, nflProjectionPeriod: ['weekly'] } },
		description: 'NFL week to request',
	},
	{
		displayName: 'Options',
		name: 'nflOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: nflShow },
		options: [
			{
				displayName: 'Expert IDs',
				name: 'expertIds',
				type: 'string',
				default: '',
				placeholder: 'e.g. 345:332:12',
				description: 'Expert IDs to filter by; multiple IDs are serialized with colons',
			},
			{
				displayName: 'Player IDs',
				name: 'playerIds',
				type: 'string',
				default: '',
				placeholder: 'e.g. 7354:6880',
				description: 'FantasyPros player IDs; multiple IDs are serialized with colons',
			},
			{
				displayName: 'Positions',
				name: 'positions',
				type: 'multiOptions',
				options: positionOptions.nfl,
				default: [],
				description: 'Additional NFL positions to filter by',
			},
		],
	},
	{
		displayName: 'Projection Type',
		name: 'mlbProjectionType',
		type: 'options',
		options: projectionTypes,
		default: 'preseason',
		displayOptions: { show: mlbShow },
		description: 'MLB projection type to request',
	},
	{
		displayName: 'Date',
		name: 'mlbDate',
		type: 'string',
		default: '',
		placeholder: 'YYYY-MM-DD',
		required: true,
		displayOptions: { show: { ...mlbShow, mlbProjectionType: ['daily'] } },
		description: 'Date for daily MLB projections in YYYY-MM-DD format',
	},
	{
		displayName: 'Week',
		name: 'mlbWeek',
		type: 'number',
		typeOptions: { minValue: 0, numberStepSize: 1 },
		default: 1,
		required: true,
		displayOptions: { show: { ...mlbShow, mlbProjectionType: ['weekly'] } },
		description: 'Non-negative week number for weekly MLB projections',
	},
	{
		displayName: 'Position',
		name: 'mlbPosition',
		type: 'options',
		options: [{ name: 'Not Set', value: '' }, ...positionOptions.mlb],
		default: '',
		displayOptions: { show: mlbShow },
		description: 'MLB position to filter by',
	},
	{
		displayName: 'Options',
		name: 'mlbOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: mlbShow },
		options: [
			{
				displayName: 'Expert IDs',
				name: 'expertIds',
				type: 'string',
				default: '',
				placeholder: 'e.g. 345:332:12',
				description: 'Expert IDs to filter by; multiple IDs are serialized with colons',
			},
			{
				displayName: 'League Key',
				name: 'leagueKey',
				type: 'string',
				default: '',
				placeholder: 'mlb~00000000-0000-0000-0000-000000000000',
				description: 'MPB/DW league key in the format documented by FantasyPros',
			},
			{
				displayName: 'Player IDs',
				name: 'playerIds',
				type: 'string',
				default: '',
				placeholder: 'e.g. 7354,6880',
				description: 'FantasyPros player IDs; multiple IDs are serialized with commas',
			},
			{
				displayName: 'Site Eligibility',
				name: 'siteEligibility',
				type: 'options',
				options: siteEligibilityOptions,
				default: 'AO',
				description: 'Fantasy site position eligibility to apply',
			},
		],
	},
	{
		displayName: 'Projection Type',
		name: 'nbaProjectionType',
		type: 'options',
		options: projectionTypes,
		default: 'preseason',
		displayOptions: { show: nbaShow },
		description: 'NBA projection type to request',
	},
	{
		displayName: 'Date',
		name: 'nbaDate',
		type: 'string',
		default: '',
		placeholder: 'YYYY-MM-DD',
		required: true,
		displayOptions: { show: { ...nbaShow, nbaProjectionType: ['daily'] } },
		description: 'Date for daily NBA projections in YYYY-MM-DD format',
	},
	{
		displayName: 'Position',
		name: 'nbaPosition',
		type: 'options',
		options: [{ name: 'Not Set', value: '' }, ...positionOptions.nba],
		default: '',
		displayOptions: { show: nbaShow },
		description: 'NBA position to filter by',
	},
	{
		displayName: 'Statistics Type',
		name: 'nbaStatisticsType',
		type: 'options',
		options: [
			{ name: 'Averages', value: 'avg' },
			{ name: 'Totals', value: 'total' },
		],
		default: 'total',
		displayOptions: { show: nbaShow },
		description: 'Whether projected statistics are returned as totals or averages',
	},
	{
		displayName: 'Precise Values',
		name: 'nbaPreciseValues',
		type: 'boolean',
		default: false,
		displayOptions: { show: nbaShow },
		description: 'Whether to request more precise projected values',
	},
	{
		displayName: 'Options',
		name: 'nbaOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: nbaShow },
		options: [
			{
				displayName: 'Expert IDs',
				name: 'expertIds',
				type: 'string',
				default: '',
				placeholder: 'e.g. 345:332:12',
				description: 'Expert IDs to filter by; multiple IDs are serialized with colons',
			},
			{
				displayName: 'Player IDs',
				name: 'playerIds',
				type: 'string',
				default: '',
				placeholder: 'e.g. 7354,6880',
				description: 'FantasyPros player IDs; multiple IDs are serialized with commas',
			},
			{
				displayName: 'Team IDs',
				name: 'teamIds',
				type: 'string',
				default: '',
				placeholder: 'e.g. 1,2',
				description: 'Numeric team IDs; multiple IDs are serialized with commas per the schema',
			},
		],
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		displayOptions: { show: resourceShow },
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 50,
		displayOptions: { show: { ...resourceShow, returnAll: [false] } },
		description: 'Max number of results to return',
	},
];
