import type { INodeProperties } from 'n8n-workflow';
import {
	currentSeason,
	positionOptions,
	rankingTypeOptions,
	scoringOptions,
	siteEligibilityOptions,
	sportOptions,
} from './Common';

const resourceShow = { resource: ['rankings'] };
const rankingsShow = { ...resourceShow, operation: ['getRankings'] };
const consensusShow = { ...resourceShow, operation: ['getConsensusRankings'] };
const expertsShow = { ...resourceShow, operation: ['getExperts'] };
const consensusAndExpertsShow = {
	resource: ['rankings'],
	operation: ['getConsensusRankings', 'getExperts'],
};

const sharedCollectionControls: INodeProperties[] = [
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		displayOptions: { show: resourceShow },
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 50,
		displayOptions: { show: { ...resourceShow, returnAll: [false] } },
		description: 'Max number of results to return',
	},
];

export const rankingsDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: resourceShow },
		options: [
			{
				name: 'Get Consensus Rankings',
				value: 'getConsensusRankings',
				action: 'Get consensus rankings',
				description: 'Get expert consensus rankings',
			},
			{
				name: 'Get Experts',
				value: 'getExperts',
				action: 'Get ranking experts',
				description: 'Get experts available for ranking sets',
			},
			{
				name: 'Get Rankings',
				value: 'getRankings',
				action: 'Get player rankings',
				description: 'Get individual expert player rankings',
			},
		],
		default: 'getRankings',
	},
	{
		displayName: 'Sport',
		name: 'sport',
		type: 'options',
		noDataExpression: true,
		options: sportOptions,
		default: 'nfl',
		displayOptions: { show: resourceShow },
		description: 'Sport to query',
	},
	{
		displayName: 'Season',
		name: 'season',
		type: 'number',
		typeOptions: { minValue: 2012, numberStepSize: 1 },
		default: currentSeason,
		displayOptions: { show: resourceShow },
		description: 'Four-digit season year',
	},
	{
		displayName: 'Position',
		name: 'position',
		type: 'options',
		options: positionOptions.nfl,
		default: 'ALL',
		required: true,
		displayOptions: { show: { ...consensusShow, sport: ['nfl'] } },
		description: 'Position supported for the selected sport',
	},
	{
		displayName: 'Position',
		name: 'position',
		type: 'options',
		options: positionOptions.mlb,
		default: 'ALL',
		required: true,
		displayOptions: { show: { ...consensusShow, sport: ['mlb'] } },
		description: 'Position supported for the selected sport',
	},
	{
		displayName: 'Position',
		name: 'position',
		type: 'options',
		options: positionOptions.nba,
		default: 'ALL',
		required: true,
		displayOptions: { show: { ...consensusShow, sport: ['nba'] } },
		description: 'Position supported for the selected sport',
	},
	{
		displayName: 'Position',
		name: 'position',
		type: 'options',
		options: positionOptions.nhl,
		default: 'ALL',
		required: true,
		displayOptions: { show: { ...consensusShow, sport: ['nhl'] } },
		description: 'Position supported for the selected sport',
	},
	{
		displayName: 'Position',
		name: 'position',
		type: 'options',
		options: [{ name: 'Not Set', value: '' }, ...positionOptions.nfl],
		default: '',
		displayOptions: { show: { ...expertsShow, sport: ['nfl'] } },
		description: 'Position supported for the selected sport',
	},
	{
		displayName: 'Position',
		name: 'position',
		type: 'options',
		options: [{ name: 'Not Set', value: '' }, ...positionOptions.mlb],
		default: '',
		displayOptions: { show: { ...expertsShow, sport: ['mlb'] } },
		description: 'Position supported for the selected sport',
	},
	{
		displayName: 'Position',
		name: 'position',
		type: 'options',
		options: [{ name: 'Not Set', value: '' }, ...positionOptions.nba],
		default: '',
		displayOptions: { show: { ...expertsShow, sport: ['nba'] } },
		description: 'Position supported for the selected sport',
	},
	{
		displayName: 'Position',
		name: 'position',
		type: 'options',
		options: [{ name: 'Not Set', value: '' }, ...positionOptions.nhl],
		default: '',
		displayOptions: { show: { ...expertsShow, sport: ['nhl'] } },
		description: 'Position supported for the selected sport',
	},
	{
		displayName: 'Ranking Type',
		name: 'rankingType',
		type: 'options',
		options: [{ name: 'Not Set', value: '' }, ...rankingTypeOptions.nfl],
		default: '',
		displayOptions: { show: { ...consensusAndExpertsShow, sport: ['nfl'] } },
		description: 'Ranking Type supported for the selected sport',
	},
	{
		displayName: 'Ranking Type',
		name: 'rankingType',
		type: 'options',
		options: [{ name: 'Not Set', value: '' }, ...rankingTypeOptions.mlb],
		default: '',
		displayOptions: { show: { ...consensusAndExpertsShow, sport: ['mlb'] } },
		description: 'Ranking Type supported for the selected sport',
	},
	{
		displayName: 'Ranking Type',
		name: 'rankingType',
		type: 'options',
		options: [{ name: 'Not Set', value: '' }, ...rankingTypeOptions.nba],
		default: '',
		displayOptions: { show: { ...consensusAndExpertsShow, sport: ['nba'] } },
		description: 'Ranking Type supported for the selected sport',
	},
	{
		displayName: 'Ranking Type',
		name: 'rankingType',
		type: 'options',
		options: [{ name: 'Not Set', value: '' }, ...rankingTypeOptions.nhl],
		default: '',
		displayOptions: { show: { ...consensusAndExpertsShow, sport: ['nhl'] } },
		description: 'Ranking Type supported for the selected sport',
	},
	{
		displayName: 'Scoring',
		name: 'scoring',
		type: 'options',
		options: [{ name: 'Not Set', value: '' }, ...scoringOptions.nfl],
		default: '',
		displayOptions: { show: { ...consensusAndExpertsShow, sport: ['nfl'] } },
		description: 'Scoring supported for the selected sport',
	},
	{
		displayName: 'Scoring',
		name: 'scoring',
		type: 'options',
		options: [{ name: 'Not Set', value: '' }, ...scoringOptions.nba],
		default: '',
		displayOptions: { show: { ...consensusAndExpertsShow, sport: ['nba'] } },
		description: 'Scoring supported for the selected sport',
	},
	...sharedCollectionControls,
	{
		displayName: 'Options',
		name: 'rankingsOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: rankingsShow },
		options: [
			{
				displayName: 'Expert IDs',
				name: 'expertIds',
				type: 'string',
				default: '',
				placeholder: 'e.g. 345:332:12',
				description:
					'Expert IDs to filter by, serialized with colons as required by the OpenAPI schema',
			},
			{
				displayName: 'Minimal Response',
				name: 'minimal',
				type: 'boolean',
				default: false,
				description: 'Whether to return reduced player detail',
			},
			{
				displayName: 'Player ID',
				name: 'playerId',
				type: 'number',
				typeOptions: { minValue: 1 },
				default: 0,
				description: 'FantasyPros player ID to filter on',
			},
			{
				displayName: 'Rank Range',
				name: 'rankRange',
				type: 'boolean',
				default: false,
				description: 'Whether to include minimum and maximum rank',
			},
			{
				displayName: 'Ranking Statistics',
				name: 'rankStats',
				type: 'boolean',
				default: false,
				description: 'Whether to include average and standard deviation',
			},
			{
				displayName: 'Week',
				name: 'week',
				type: 'number',
				typeOptions: { minValue: 0, maxValue: 22, numberStepSize: 1 },
				default: 0,
				description: 'Week to request, where 0 represents preseason',
			},
		],
	},
	{
		displayName: 'Include Drafters Ranking Type',
		name: 'useDraftersType',
		type: 'boolean',
		default: false,
		displayOptions: { show: { ...rankingsShow, sport: ['nfl'] } },
		description: 'Whether to request the NFL Drafters ranking type',
	},
	{
		displayName: 'MLB Site Eligibility',
		name: 'siteEligibility',
		type: 'options',
		options: [{ name: 'Not Set', value: '' }, ...siteEligibilityOptions],
		default: '',
		displayOptions: { show: { ...rankingsShow, sport: ['mlb'] } },
		description: 'Fantasy site position eligibility to apply',
	},
	{
		displayName: 'Options',
		name: 'consensusOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: consensusShow },
		options: [
			{
				displayName: 'Expert Detail Mode',
				name: 'expertDetails',
				type: 'options',
				options: [
					{ name: 'Available', value: 'available' },
					{ name: 'Show', value: 'show' },
				],
				default: 'show',
				description: 'Expert details to include in the response',
			},
			{
				displayName: 'Expert IDs',
				name: 'expertIds',
				type: 'string',
				default: '',
				placeholder: 'e.g. 345:332:12',
				description: 'Expert IDs to filter by, serialized with colons',
			},
			{
				displayName: 'Include IDP',
				name: 'includeIdp',
				type: 'boolean',
				default: false,
				displayOptions: { show: { '/sport': ['nfl'] } },
				description: 'Whether to include individual defensive players for NFL',
			},
			{
				displayName: 'Week',
				name: 'week',
				type: 'number',
				typeOptions: { minValue: 0, maxValue: 22, numberStepSize: 1 },
				default: 0,
				displayOptions: { show: { '/sport': ['nfl'] } },
				description: 'NFL week, where 0 represents preseason',
			},
		],
	},
	{
		displayName: 'Include Overall Ranking Accuracy',
		name: 'includeOverall',
		type: 'boolean',
		default: false,
		displayOptions: { show: expertsShow },
		description: 'Whether to include overall ranking accuracy in the expert response',
	},
];
